### ISSUE TITLE
天津的明细和总的确诊数有差异

### ISSUE THREAD

**Issue by jackberry** [Avens666/COVID-19-2019-nCoV-Infection-Data-cleaning-#1]

**Comment by jackberry** [comment]
天津新增治愈和累计治愈这两个数据有差异。

**Comment by Avens666** [comment]
谢谢反馈，确实，新增数据和累计数据现在有对不齐的问题，
这个问题是由于源数据中累计数据存在孤立值，有的城市今天有值明天没有值（可能计算到其他地方了），导致用当天减去前一天这个算法不能处理这种情况。 还在想办法解决中

**Comment by Avens666** [comment]
更新了脚本和数据，解决了新增数据计算问题，更新后的数据也更准确了，可参看readme
