### ISSUE TITLE
继续更新啊老铁

### ISSUE THREAD

**Issue by dcdlove** [Avens666/COVID-19-2019-nCoV-Infection-Data-cleaning-#4]

**Comment by Avens666** [comment]
呵呵明天更新。
今天写文章去了。
https://www.yuque.com/docs/share/57451c11-9a33-460c-81bc-2ee24b38b94f?#


不过现在武汉市外的数据大部分清零。其实手动更新都忙得过来哟。

---原始邮件---
发件人: "Jaly"<notifications@github.com&gt;
发送时间: 2020年3月3日(周二) 晚上6:12
收件人: "Avens666/COVID-19-2019-nCoV-Infection-Data-cleaning-"<COVID-19-2019-nCoV-Infection-Data-cleaning-@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Avens666/COVID-19-2019-nCoV-Infection-Data-cleaning-] 继续更新啊老铁 (#4)
