### ISSUE TITLE
nCov_world_0516.csv 中国3-17 至4-27累计确诊数据错误 

### ISSUE THREAD

**Issue by TjFish** [Avens666/COVID-19-2019-nCoV-Infection-Data-cleaning-#7]
nCov_world_0516.csv 中国3-17 至4-27累计确诊数据错误 
3-17 至4-27 中国确诊人数达15w，但实际中国确诊人数不多于9w
猜测原因是每日累计数据有问题

**Comment by Avens666** [comment]
世界数据处理是别人提交的，中国数据就不要参考这个文件了，对于中国求单纯的城市和肯定不准确
中国还是用我的俩个脚本保险

**Comment by TjFish** [comment]
OK，感谢
